### PR TITLE
fix: compatible with qq browser on ios, close #294

### LINKED ISSUE #294: QQ / UC browser support
### Environment

QQ Browser - 14.3.1.5647

UC Browser

### Reproduction

https://github.com/xjccc/useAsyncData-example

### Describe the bug

on `QQ Browser` and `UC Browser` has no result

on `safari chrome quark firefox` works fine

to add this `QQ` and `UC` works fine

```
"pnpm": {
  "overrides": {
    "ofetch": "1.2.1"
  }
}
```

is this has something affect in v1.3.3?

### Additional context

its the right 

image

on `QQ` and `UC`

image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by markthree**
### 🔗 Linked issue

#294 

nuxt/nuxt/issues/25956

nuxt/nuxt/issues/24229

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This doesn't look perfect, but after manual testing, everything runs smoothly and there are no break change.

The reason may be that the core used by these browsers has not yet implemented `response.body` 🤣

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for the PR. I would love to have further investigation before merging this (otherwise ofetch ends up with lots of old browser compatibility fixes) 

Do you mind to make a minimal testing environment (html+js) and share the browser version/platform required to verify.

**Comment by pi0** [comment]
Okay, no worries. I will try to assemble a reproduction env once could but it is essential before we can move it forward I hope it is reasonable.

**Comment by markthree** [comment]
> Okay, no worries. I will try to assemble a reproduction env once could but it is essential before we can move it forward I hope it is reasonable.
Thank you 🥰

**Comment by zhangjunjie6b** [comment]
So has this problem been resolved? I've been waiting for the new version 🙂

**Comment by markthree** [comment]
If someone doesn't have high stability requirements, they can use this module → [markthree/nuxt-fix-ofetch](https://github.com/markthree/nuxt-fix-ofetch)

**Comment by pi0** [comment]
Seems to be fixed in the latest QQ browser @markthree can you confirm?

https://github.com/unjs/ofetch/issues/294#issuecomment-2167757063

**Comment by markthree** [comment]
> Seems to be fixed in the latest QQ browser @markthree can you confirm?
> 
> [#294 (comment)](https://github.com/unjs/ofetch/issues/294#issuecomment-2167757063)

Yes, the problem still exists, it's a problem with ofetch, and it can be reproduced when using it solely

**Comment by pi0** [comment]
From @xjccc comment:

> now..
> QQ version: 15.1.6.5925
> UC version: 16.5.5.2341
> works fine

But you have issue with these versions and ofetch?

**Comment by markthree** [comment]
> From @xjccc comment:
> 
> > now..
> > QQ version: 15.1.6.5925
> > UC version: 16.5.5.2341
> > works fine
> 
> But you have issue with these versions and ofetch?

yes, QQ Browser version: 15.1.7

**Comment by markthree** [comment]
Thanks to the `onResponse` option, I'm now using it to hack in my production environment, and so far I've found no problems! 🤣

ref → [nuxt-fix-ofetch/src/runtime/00.fetch.client.ts#L52-#L86](https://github.com/markthree/nuxt-fix-ofetch/blob/deeed4e1805d682d89fbc8a4dd2359806ae0a010/src/runtime/00.fetch.client.ts#L52-#L86)

**Comment by xjccc** [comment]
I upgrade my QQ Browser version: 15.1.7.5928

iOS version: 17.5.1

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.4
------------------------------
my web site works fine..

**Comment by pi0** [comment]
Hi dear @markthree  Again sorry this took long. 

We have merged a relative fix in https://github.com/unjs/ofetch/pull/398 that passes `_bodyInit` directly as `_data`.

I'm not sure for using `.stream`, seems none of the BodyInit types in the Fetch API have a `.stream()` method. 

Closing since #398 is merged. If you could try and had any findings, (specially on stream normalization) please mention or feel free to make a new PR.

**Comment by markthree** [comment]
> Hi dear @markthree Again sorry this took long.
> 
> We have merged a relative fix in #398 that passes `_bodyInit` directly as `_data`.
> 
> I think we might add an improvement to check if body is blob, use .stream()

Thanks @pi0, looks great, ofetch is much easier to use.

**Comment by markthree** [comment]
> Hi dear @markthree Again sorry this took long.
> 
> We have merged a relative fix in #398 that passes `_bodyInit` directly as `_data`.
> 
> I think we might add an improvement to check if body is blob, use .stream()

Thanks @pi0, looks great, ofetch is much easier to use.

**Pull request closed without merging**
